delimiter $$

CREATE TABLE `AllTheWIM` (
  `record_type` varchar(1) DEFAULT NULL,
  `state_fips` varchar(2) DEFAULT NULL,
  `station_id` varchar(6) DEFAULT NULL,
  `direction` decimal(1,0) DEFAULT NULL,
  `lane` int(1) DEFAULT NULL,
  `year` int(2) DEFAULT NULL,
  `month` int(2) DEFAULT NULL,
  `day` int(2) DEFAULT NULL,
  `hour` int(2) DEFAULT NULL,
  `vehicle_class` int(2) DEFAULT NULL,
  `unused` int(3) DEFAULT NULL,
  `total_weight` int(4) DEFAULT NULL,
  `number_axles` int(2) DEFAULT NULL,
  `A_weight` int(3) DEFAULT NULL,
  `AB_axle` int(3) DEFAULT NULL,
  `B_weight` int(3) DEFAULT NULL,
  `BC_axle` int(3) DEFAULT NULL,
  `C_weight` int(3) DEFAULT NULL,
  `CD_axle` int(3) DEFAULT NULL,
  `D_weight` int(3) DEFAULT NULL,
  `DE_axle` int(3) DEFAULT NULL,
  `E_weight` int(3) DEFAULT NULL,
  `EF_axle` int(3) DEFAULT NULL,
  `F_weight` int(3) DEFAULT NULL,
  `FG_axle` int(3) DEFAULT NULL,
  `G_weight` int(3) DEFAULT NULL,
  `GH_axle` int(3) DEFAULT NULL,
  `H_weight` int(3) DEFAULT NULL,
  `HI_axle` int(3) DEFAULT NULL,
  `I_weight` int(3) DEFAULT NULL,
  `IJ_axle` int(3) DEFAULT NULL,
  `J_weight` int(3) DEFAULT NULL,
  `JK_axle` int(3) DEFAULT NULL,
  `K_weight` int(3) DEFAULT NULL,
  `KL_axle` int(3) DEFAULT NULL,
  `L_weight` int(3) DEFAULT NULL,
  `LM_axle` int(3) DEFAULT NULL,
  `M_weight` int(3) DEFAULT NULL,
  KEY `state` (`state_fips`),
  KEY `station` (`station_id`),
  KEY `class` (`vehicle_class`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$

